### PR TITLE
Followed platform conventions for showing search shortcut key

### LINKED ISSUE #1960: Docs searchbox shortcut formatted wrong on Mac
(This is a minor nit, but I didn't want to open a PR without a matching issue.)

In the documentation site searchbox, the placeholder currently displays its shortcut as "(⌘ + K)" on macOS and "(Ctrl + K)" elsewhere.

Using "+" like that is very much a Windows convention. Macs use just the key symbol without a plus sign: "⌘ K".

Mac (Safari):
Screenshot of Mac Safari on docs.djangoproject.com, highlighting shortcut keys in the Edit menu shown without plus signs, and the ⌘ + K shortcut shown in the site's searchbox

Windows (Edge):
Screenshot of Windows Edge on docs.djangoproject.com, highlighting shortcut keys in the three-dot menu shown with plus signs, and the Ctrl + K) shown in the site's searchbox

(Also, Windows apps don't typically use spaces around the plus sign: "Ctrl+K".)

### PR DESCRIPTION
**Pull request by medmunds**
Changed display of the search shortcut key to "⌘ K" on Mac and "Ctrl+K" elsewhere.

Fixes #1960.

### CODE REVIEW

File: djangoproject/static/js/djangoproject.js [hunk 1]
```diff
@@ -75,7 +75,8 @@ document.querySelector('.menu-button').addEventListener('click', function () {
 
   const original_placeholder = el.getAttribute('placeholder');
   const is_mac = navigator.userAgent.indexOf('Mac') !== -1;
-  const new_value = `${original_placeholder} (${is_mac ? '⌘' : 'Ctrl'} + K)`;
+  // \u202f is a narrow no-break space
```
Comment (adamzap) [inline djangoproject/static/js/djangoproject.js:78]: Could we drop this comment?

**Review by adamzap — CHANGES_REQUESTED** [review]
Thanks for this suggestion!

File: djangoproject/static/js/djangoproject.js (hunk 1 above)
Comment (medmunds) [reply djangoproject/static/js/djangoproject.js]: Done. (Moved the explanation into the commit message.)

**Comment by medmunds** [comment]
I went with a hair space between the ⌘ and the K. A full space seemed too wide and no space seemed too narrow.

Screenshot of search box in Safari comparing spacing between ⌘ and K, for full space, thin space, hair space, and no space

File: djangoproject/static/js/djangoproject.js (hunk 1 above)
Comment (adamzap) [reply djangoproject/static/js/djangoproject.js]: Thank you!
